<?php

return [
    'permission_list' => [
        [
            "id"           => "1",
            "parent_id"    => "0",
            "name"         => "Api:setting",
            "display_name" => "Setting",
            "display_desc" => "",
            "url"          => "/setting",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "setting-color",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "2",
            "parent_id"    => "1",
            "name"         => "Api:setting/user_module",
            "display_name" => "User Module",
            "display_desc" => "",
            "url"          => "/setting/user_module",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "user",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "3",
            "parent_id"    => "2",
            "name"         => "Api:setting/user_module/user",
            "display_name" => "User Management",
            "display_desc" => "Manage the background users",
            "url"          => "/setting/user_module/user/list",
            "component"    => "setting/user_module/user/index",
            "guard_name"   => "web",
            "icon"         => "product-list",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "4",
            "parent_id"    => "3",
            "name"         => "Api:setting/user_module/user/list-index",
            "display_name" => "User List",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "5",
            "parent_id"    => "3",
            "name"         => "Api:setting/user_module/user/store-store",
            "display_name" => "User Add",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "6",
            "parent_id"    => "3",
            "name"         => "Api:setting/user_module/user/update-update",
            "display_name" => "User Edit",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "7",
            "parent_id"    => "3",
            "name"         => "Api:setting/user_module/user/destroy-destroy",
            "display_name" => "User Delete",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "8",
            "parent_id"    => "3",
            "name"         => "Api:setting/user_module/user/change_status-changeStatus",
            "display_name" => "User change status",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "9",
            "parent_id"    => "3",
            "name"         => "Api:setting/user_module/permission/accord_user_permission-accordUserPermission",
            "display_name" => "User Permissions",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "10",
            "parent_id"    => "3",
            "name"         => "Api:setting/user_module/user/reset_password-resetPassword",
            "display_name" => "Reset Password",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "11",
            "parent_id"    => "2",
            "name"         => "Api:setting/user_module/role",
            "display_name" => "Role Management",
            "display_desc" => "Manage the background role",
            "url"          => "/setting/user_module/role/list",
            "component"    => "setting/user_module/role/index",
            "guard_name"   => "web",
            "icon"         => "role",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "2",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "12",
            "parent_id"    => "11",
            "name"         => "Api:setting/user_module/role/list-index",
            "display_name" => "Role List",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "13",
            "parent_id"    => "11",
            "name"         => "Api:setting/user_module/role/store-store",
            "display_name" => "Role Add",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "14",
            "parent_id"    => "11",
            "name"         => "Api:setting/user_module/role/update-update",
            "display_name" => "Role Edit",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "15",
            "parent_id"    => "11",
            "name"         => "Api:setting/user_module/role/destroy-destroy",
            "display_name" => "Role Delete",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "16",
            "parent_id"    => "11",
            "name"         => "Api:setting/user_module/permission/accord_role_permission-accordRolePermission",
            "display_name" => "Role Permission",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "17",
            "parent_id"    => "2",
            "name"         => "Api:setting/user_module/permission",
            "display_name" => "Permission Management",
            "display_desc" => "Manage the background authority/menu",
            "url"          => "/setting/user_module/permission/list",
            "component"    => "setting/user_module/permission/index",
            "guard_name"   => "web",
            "icon"         => "permission",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "3",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "18",
            "parent_id"    => "17",
            "name"         => "Api:setting/user_module/permission/list-index",
            "display_name" => "Permission List",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "19",
            "parent_id"    => "17",
            "name"         => "Api:setting/user_module/permission/store-store",
            "display_name" => "Permission Add",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "20",
            "parent_id"    => "17",
            "name"         => "Api:setting/user_module/permission/update-update",
            "display_name" => "Permission Edit",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "21",
            "parent_id"    => "17",
            "name"         => "Api:setting/user_module/permission/destroy-destroy",
            "display_name" => "Permission Delete",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "22",
            "parent_id"    => "1",
            "name"         => "Api:setting/monitoring_module",
            "display_name" => "System monitoring",
            "display_desc" => "",
            "url"          => "/setting/monitoring_module",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "monitoring_module",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "2",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "23",
            "parent_id"    => "22",
            "name"         => "Api:setting/monitoring_module/serve-serve",
            "display_name" => "Serve monitoring",
            "display_desc" => "Record the system configuration information, etc.",
            "url"          => "/setting/monitoring_module/serve",
            "component"    => "setting/monitoring_module/serve/index",
            "guard_name"   => "web",
            "icon"         => "serve",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "24",
            "parent_id"    => "22",
            "name"         => "Api:setting/monitoring_module/timed_task",
            "display_name" => "Time task",
            "display_desc" => "Configure the timing task of the system",
            "url"          => "/setting/monitoring_module/crontab",
            "component"    => "setting/monitoring_module/crontab/index",
            "guard_name"   => "web",
            "icon"         => "crontab",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "2",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "25",
            "parent_id"    => "24",
            "name"         => "Api:setting/monitoring_module/timed_task/list-index",
            "display_name" => "Time Task List",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "26",
            "parent_id"    => "24",
            "name"         => "Api:setting/monitoring_module/timed_task/store-store",
            "display_name" => "Time Task Add",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "27",
            "parent_id"    => "24",
            "name"         => "Api:setting/monitoring_module/timed_task/update-update",
            "display_name" => "Time Task Edit",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "28",
            "parent_id"    => "24",
            "name"         => "Api:setting/monitoring_module/timed_task/destroy-destroy",
            "display_name" => "Time Task Delete",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "29",
            "parent_id"    => "24",
            "name"         => "Api:setting/monitoring_module/timed_task/change_status-changeStatus",
            "display_name" => "Time Task Change Status",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "30",
            "parent_id"    => "1",
            "name"         => "Api:setting/system_module",
            "display_name" => "System Management",
            "display_desc" => "",
            "url"          => "/setting/system_module",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "system_module",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "3",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "31",
            "parent_id"    => "30",
            "name"         => "Api:setting/system_module/dict_type",
            "display_name" => "Dictionary Management",
            "display_desc" => "Configuration system enumeration items",
            "url"          => "/setting/system_module/dict/list",
            "component"    => "setting/system_module/dict/index",
            "guard_name"   => "web",
            "icon"         => "dict",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "32",
            "parent_id"    => "31",
            "name"         => "Api:setting/system_module/dict_type/list-index",
            "display_name" => "Dictionary List",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "33",
            "parent_id"    => "31",
            "name"         => "Api:setting/system_module/dict_type/store-store",
            "display_name" => "Dictionary Add",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "34",
            "parent_id"    => "31",
            "name"         => "Api:setting/system_module/dict_type/update-update",
            "display_name" => "Dictionary Edit",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "35",
            "parent_id"    => "31",
            "name"         => "Api:setting/system_module/dict_type/destroy-destroy",
            "display_name" => "Dictionary Delete",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "36",
            "parent_id"    => "30",
            "name"         => "Api:setting/system_module/dict_data",
            "display_name" => "Dictionary Data",
            "display_desc" => "Dictionary data list",
            "url"          => "/setting/system_module/dict_data/list/:dict_id",
            "component"    => "setting/system_module/dict/data",
            "guard_name"   => "web",
            "icon"         => "dict",
            "type"         => "2",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "37",
            "parent_id"    => "36",
            "name"         => "Api:setting/system_module/dict_data/list-index",
            "display_name" => "Dictionary Data List",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "38",
            "parent_id"    => "36",
            "name"         => "Api:setting/system_module/dict_data/store-store",
            "display_name" => "Dictionary Data Add",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "39",
            "parent_id"    => "36",
            "name"         => "Api:setting/system_module/dict_data/update-update",
            "display_name" => "Dictionary Data Edit",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "40",
            "parent_id"    => "36",
            "name"         => "Api:setting/system_module/dict_data/destory-destroy",
            "display_name" => "Dictionary Data Delete",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "41",
            "parent_id"    => "30",
            "name"         => "Api:setting/system_module/global_config",
            "display_name" => "Parameter Settings",
            "display_desc" => "Some commonly used parameters in the configuration item",
            "url"          => "/setting/system_module/global_config/config/list",
            "component"    => "setting/system_module/globalConfig/index",
            "guard_name"   => "web",
            "icon"         => "config",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "2",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "42",
            "parent_id"    => "41",
            "name"         => "Api:setting/system_module/global_config/list-index",
            "display_name" => "Parameter List",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "43",
            "parent_id"    => "41",
            "name"         => "Api:setting/system_module/global_config/store-store",
            "display_name" => "Parameter Add",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "44",
            "parent_id"    => "41",
            "name"         => "Api:setting/system_module/global_config/update-update",
            "display_name" => "Parameter Edit",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "45",
            "parent_id"    => "41",
            "name"         => "Api:setting/system_module/global_config/destroy-destroy",
            "display_name" => "Parameter Delete",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "46",
            "parent_id"    => "30",
            "name"         => "Api:setting/system_module/notice",
            "display_name" => "Notification Management",
            "display_desc" => "Some broadcast notifications of the system",
            "url"          => "/setting/system_module/notice",
            "component"    => "setting/system_module/notice",
            "guard_name"   => "web",
            "icon"         => "notice",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "3",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "47",
            "parent_id"    => "46",
            "name"         => "Api:setting/system_module/notice/list-index",
            "display_name" => "Notification List",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "48",
            "parent_id"    => "46",
            "name"         => "Api:setting/system_module/notice/store-store",
            "display_name" => "Notification Add",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "49",
            "parent_id"    => "46",
            "name"         => "Api:setting/system_module/notice/update-update",
            "display_name" => "Notification Edit",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "50",
            "parent_id"    => "46",
            "name"         => "Api:setting/system_module/notice/destroy-destroy",
            "display_name" => "Notification Delete",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "51",
            "parent_id"    => "30",
            "name"         => "Api:setting/system_module/advice",
            "display_name" => "System Advice",
            "display_desc" => "Provide users to feedback bugs and optimize demand",
            "url"          => "/setting/system_module/advice",
            "component"    => "setting/system_module/advice",
            "guard_name"   => "web",
            "icon"         => "form",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "4",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "52",
            "parent_id"    => "51",
            "name"         => "Api:setting/system_module/advice/list-index",
            "display_name" => "System Advice List",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "53",
            "parent_id"    => "51",
            "name"         => "Api:setting/system_module/advice/store-store",
            "display_name" => "System Advice Add",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "54",
            "parent_id"    => "51",
            "name"         => "Api:setting/system_module/advice/update-update",
            "display_name" => "System Advice Edit",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "55",
            "parent_id"    => "51",
            "name"         => "Api:setting/system_module/advice/destroy-destroy",
            "display_name" => "System Advice Delete",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "56",
            "parent_id"    => "51",
            "name"         => "Api:setting/system_module/advice/reply-reply",
            "display_name" => "System Advice Reply",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "57",
            "parent_id"    => "1",
            "name"         => "Api:setting/log_module",
            "display_name" => "Log Management",
            "display_desc" => "",
            "url"          => "/setting/log_module",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "log",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "4",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "58",
            "parent_id"    => "57",
            "name"         => "Api:setting/log_module/operate_log/list-index",
            "display_name" => "Operate Log List",
            "display_desc" => "Record some of the behavior logs of the user",
            "url"          => "/setting/log_module/operate_log/list",
            "component"    => "setting/log_module/operateLog",
            "guard_name"   => "web",
            "icon"         => "operateLog",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "59",
            "parent_id"    => "57",
            "name"         => "Api:setting/log_module/login_log/list-index",
            "display_name" => "Login Log List",
            "display_desc" => "Record user login information",
            "url"          => "/setting/log_module/login_log/list",
            "component"    => "setting/log_module/loginLog",
            "guard_name"   => "web",
            "icon"         => "loginLog",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "2",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "60",
            "parent_id"    => "57",
            "name"         => "Api:setting/log_module/system_log",
            "display_name" => "System Log",
            "display_desc" => "System framework log and error log",
            "url"          => "/setting/log_module/system_log/list",
            "component"    => "setting/log_module/systemLog",
            "guard_name"   => "web",
            "icon"         => "logs",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "3",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "61",
            "parent_id"    => "60",
            "name"         => "Api:setting/log_module/system_log/log_path-getLogPath",
            "display_name" => "System Log Path",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "62",
            "parent_id"    => "60",
            "name"         => "Api:setting/log_module/system_log/destroy_log-deleteLog",
            "display_name" => "System Log Delete",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "63",
            "parent_id"    => "1",
            "name"         => "Api:setting/technique_module",
            "display_name" => "Technical Support",
            "display_desc" => "",
            "url"          => "/setting/technique_module",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "technique",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "5",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "64",
            "parent_id"    => "63",
            "name"         => "Api:setting/technique_module/form_build-formBuild",
            "display_name" => "Form Builder",
            "display_desc" => "Quickly generate a form",
            "url"          => "/setting/technique_module/form_build",
            "component"    => "setting/technique_module/formBuild",
            "guard_name"   => "web",
            "icon"         => "form",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "65",
            "parent_id"    => "63",
            "name"         => "Api:setting/technique_module/json_decode-jsonDecode",
            "display_name" => "Json Decode",
            "display_desc" => "Utilized JSON expression",
            "url"          => "/setting/technique_module/json_decode",
            "component"    => "setting/technique_module/jsonDecode",
            "guard_name"   => "web",
            "icon"         => "jsonDecode",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "2",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "66",
            "parent_id"    => "0",
            "name"         => "Api:blog",
            "display_name" => "Blog",
            "display_desc" => "",
            "url"          => "/blog",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "blog-color",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "2",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "67",
            "parent_id"    => "66",
            "name"         => "Api:blog/picture_module",
            "display_name" => "Picture Module",
            "display_desc" => "Picture resources of the album website",
            "url"          => "/blog/picture_module",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "pictureBed",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "68",
            "parent_id"    => "67",
            "name"         => "Api:blog/picture_module/album",
            "display_name" => "Album Management",
            "display_desc" => "Album module management",
            "url"          => "/blog/picture_module/album",
            "component"    => "blog/picture_module/album",
            "guard_name"   => "web",
            "icon"         => "album",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "69",
            "parent_id"    => "68",
            "name"         => "Api:blog/picture_module/album/list-index",
            "display_name" => "Album List",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "70",
            "parent_id"    => "68",
            "name"         => "Api:blog/picture_module/album/store-store",
            "display_name" => "Album Add",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "71",
            "parent_id"    => "68",
            "name"         => "Api:blog/picture_module/album/update-update",
            "display_name" => "Album Edit",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "72",
            "parent_id"    => "68",
            "name"         => "Api:blog/picture_module/album/destroy-destroy",
            "display_name" => "Album Delete",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "73",
            "parent_id"    => "67",
            "name"         => "Api:blog/picture_module/photo",
            "display_name" => "Photo Module",
            "display_desc" => "Image management module",
            "url"          => "/blog/picture_module/photo",
            "component"    => "blog/picture_module/photo",
            "guard_name"   => "web",
            "icon"         => "image",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "2",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "74",
            "parent_id"    => "73",
            "name"         => "Api:blog/picture_module/photo/list-index",
            "display_name" => "Photo List",
            "display_desc" => "",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "75",
            "parent_id"    => "73",
            "name"         => "Api:blog/picture_module/photo/destroy-destroy",
            "display_name" => "Photo Delete",
            "display_desc" => "Delete the picture module",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "1",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2020-6-10 00:00:00",
            "updated_at"   => "2020-6-10 00:00:00"
        ],
        [
            "id"           => "76",
            "parent_id"    => "63",
            "name"         => "Api:setting/technique_module/control",
            "display_name" => "Control Module",
            "display_desc" => "Some of the lights used to control the background of the project and some configuration options",
            "url"          => "/setting/technique_module/control",
            "component"    => "setting/technique_module/control/",
            "guard_name"   => "web",
            "icon"         => "swagger",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "3",
            "created_at"   => "2021-6-17 09:48:18",
            "updated_at"   => "2021-6-17 16:39:24"
        ],
        [
            "id"           => "77",
            "parent_id"    => "76",
            "name"         => "Api:setting/technique_module/control/list-getConfigList",
            "display_name" => "Control List",
            "display_desc" => "Get the button list",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-6-17 16:38:33",
            "updated_at"   => "2021-6-17 16:38:33"
        ],
        [
            "id"           => "78",
            "parent_id"    => "76",
            "name"         => "Api:setting/technique_module/control/change_control-changeControl",
            "display_name" => "Control Change",
            "display_desc" => "Modify the button switch",
            "url"          => "",
            "component"    => "",
            "guard_name"   => "web",
            "icon"         => "",
            "type"         => "3",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-6-17 16:39:18",
            "updated_at"   => "2021-6-17 16:39:18"
        ],
        [
            "id"           => "79",
            "parent_id"    => "0",
            "name"         => "Api:data",
            "display_name" => "Data",
            "display_desc" => "Data module",
            "url"          => "/data",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "chart",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "2",
            "created_at"   => "2021-7-29 14:31:50",
            "updated_at"   => "2021-7-29 14:32:03"
        ],
        [
            "id"           => "80",
            "parent_id"    => "79",
            "name"         => "Api:data/table_data",
            "display_name" => "Table Data",
            "display_desc" => "Tables related data display",
            "url"          => "/data/table_data",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "table",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-8-11 14:24:11",
            "updated_at"   => "2021-8-11 14:24:31"
        ],
        [
            "id"           => "81",
            "parent_id"    => "79",
            "name"         => "Api:data/chart_data",
            "display_name" => "Chart data",
            "display_desc" => "Some display data of the chart",
            "url"          => "/data/chart_data",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "monitor",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-8-11 14:26:53",
            "updated_at"   => "2021-8-11 14:26:53"
        ],
        [
            "id"           => "82",
            "parent_id"    => "80",
            "name"         => "Api:data/table_data/basic_data",
            "display_name" => "Basic table",
            "display_desc" => "Basic table data display",
            "url"          => "/data/table_data/basic_data",
            "component"    => "data/table/basic_data",
            "guard_name"   => "web",
            "icon"         => "build",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "99",
            "created_at"   => "2021-8-11 15:52:12",
            "updated_at"   => "2021-8-11 15:52:12"
        ],
        [
            "id"           => "83",
            "parent_id"    => "0",
            "name"         => "Api:laboratory",
            "display_name" => "Experiment",
            "display_desc" => "Some special function modules, such as Bilibili assistant",
            "url"          => "/laboratory",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "experiment-color",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "4",
            "created_at"   => "2021-8-20 11:02:17",
            "updated_at"   => "2021-8-20 11:02:29"
        ],
        [
            "id"           => "84",
            "parent_id"    => "83",
            "name"         => "Api:laboratory/bilibili_module",
            "display_name" => "Bilibili Assistant",
            "display_desc" => "Bilibili Assistant, providing data analysis function",
            "url"          => "/laboratory/bilibili_module",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "bilibili",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2021-8-20 11:05:01",
            "updated_at"   => "2021-8-20 15:30:23"
        ],
        [
            "id"           => "86",
            "parent_id"    => "84",
            "name"         => "Api:laboratory/bilibili_module/up_user",
            "display_name" => "User data analysis",
            "display_desc" => "Used to analyze the data of UP users",
            "url"          => "/laboratory/bilibili_module/up_user",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "up_user",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2021-8-20 11:15:33",
            "updated_at"   => "2021-8-20 15:30:29"
        ],
        [
            "id"           => "87",
            "parent_id"    => "86",
            "name"         => "Api:laboratory/bilibili_module/up_user/up_user_add-upUserAdd",
            "display_name" => "UP main entry",
            "display_desc" => "Page used to add UP master",
            "url"          => "/laboratory/bilibili_module/up_user/up_user_add",
            "component"    => "laboratory/bilibili_module/upUser/upUserAdd",
            "guard_name"   => "web",
            "icon"         => "group_manager_add",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2021-8-20 11:18:37",
            "updated_at"   => "2021-8-20 15:31:40"
        ],
        [
            "id"           => "88",
            "parent_id"    => "86",
            "name"         => "Api:laboratory/bilibili_module/up_user/up_user-upUserList",
            "display_name" => "UP main list",
            "display_desc" => "List of data information of up master",
            "url"          => "/laboratory/bilibili_module/up_user/up_user",
            "component"    => "laboratory/bilibili_module/upUser/upUser",
            "guard_name"   => "web",
            "icon"         => "user_list",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "2",
            "created_at"   => "2021-8-23 11:15:18",
            "updated_at"   => "2021-8-23 11:15:18"
        ],
        [
            "id"           => "89",
            "parent_id"    => "86",
            "name"         => "Api:laboratory/bilibili_module/up_user/up_user_chart_trend-upUserChartTrend",
            "display_name" => "UP main data trend",
            "display_desc" => "Record the trend diagram of the main personal information data of the UP",
            "url"          => "/laboratory/bilibili_module/up_user/up_user_chart_trend",
            "component"    => "laboratory/bilibili_module/upUser/upUserChartTrend",
            "guard_name"   => "web",
            "icon"         => "statistics",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "3",
            "created_at"   => "2021-8-23 14:39:21",
            "updated_at"   => "2021-8-23 14:46:19"
        ],
        [
            "id"           => "93",
            "parent_id"    => "86",
            "name"         => "Api:laboratory/bilibili_module/up_user/up_user_data_report-upUserDataReport",
            "display_name" => "UP main data report",
            "display_desc" => "Record UP main data report",
            "url"          => "/laboratory/bilibili_module/up_user/up_user_data_report",
            "component"    => "laboratory/bilibili_module/upUser/upUserDataReport",
            "guard_name"   => "web",
            "icon"         => "chart",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "4",
            "created_at"   => "2021-8-24 15:07:32",
            "updated_at"   => "2021-8-24 15:07:32"
        ],
        [
            "id"           => "94",
            "parent_id"    => "84",
            "name"         => "Api:laboratory/bilibili_module/video",
            "display_name" => "Video data analysis",
            "display_desc" => "Bilibili's video data analysis module",
            "url"          => "/laboratory/bilibili_module/video",
            "component"    => "Layout",
            "guard_name"   => "web",
            "icon"         => "video",
            "type"         => "1",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "2",
            "created_at"   => "2021-8-24 15:22:31",
            "updated_at"   => "2021-8-24 15:22:31"
        ],
        [
            "id"           => "95",
            "parent_id"    => "94",
            "name"         => "Api:laboratory/bilibili_module/video/video_add-videoAdd",
            "display_name" => "Video entry",
            "display_desc" => "Export video links into video data",
            "url"          => "/laboratory/bilibili_module/video/video_add",
            "component"    => "laboratory/bilibili_module/video/videoAdd",
            "guard_name"   => "web",
            "icon"         => "upload",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2021-8-24 15:24:50",
            "updated_at"   => "2021-8-24 15:24:50"
        ],
        [
            "id"           => "96",
            "parent_id"    => "94",
            "name"         => "Api:laboratory/bilibili_module/video/video-videoList",
            "display_name" => "Video list",
            "display_desc" => "Video data list",
            "url"          => "/laboratory/bilibili_module/video/video",
            "component"    => "laboratory/bilibili_module/video/video",
            "guard_name"   => "web",
            "icon"         => "tableList",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "1",
            "created_at"   => "2021-8-24 15:24:50",
            "updated_at"   => "2021-8-24 15:24:50"
        ],
        [
            "id"           => "97",
            "parent_id"    => "94",
            "name"         => "Api:laboratory/bilibili_module/video/video_chart_trend-videoChartTrend",
            "display_name" => "Video data trend",
            "display_desc" => "Record the trend chart of video data",
            "url"          => "/laboratory/bilibili_module/video/video_chart_trend",
            "component"    => "laboratory/bilibili_module/video/videoChartTrend",
            "guard_name"   => "web",
            "icon"         => "statistics",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "3",
            "created_at"   => "2021-8-23 14:39:21",
            "updated_at"   => "2021-8-23 14:46:19"
        ],
        [
            "id"           => "98",
            "parent_id"    => "94",
            "name"         => "Api:laboratory/bilibili_module/video/video_data_report-videoDataReport",
            "display_name" => "Video Data Report",
            "display_desc" => "Record video data report",
            "url"          => "/laboratory/bilibili_module/video/video_data_report",
            "component"    => "laboratory/bilibili_module/video/videoDataReport",
            "guard_name"   => "web",
            "icon"         => "chart",
            "type"         => "2",
            "hidden"       => "0",
            "status"       => "1",
            "sort"         => "4",
            "created_at"   => "2021-8-24 15:07:32",
            "updated_at"   => "2021-8-24 15:07:32"
        ]

    ]
];